"""users salons events tables

Revision ID: d0cb962ad167
Revises: 30ac6ed772a5
Create Date: 2021-01-26 19:33:05.574003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0cb962ad167'
down_revision = '30ac6ed772a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=True)
    op.create_table('salon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('salon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_datetime'), 'event', ['datetime'], unique=False)
    op.create_table('master_salon',
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salon.id'], ),
    sa.PrimaryKeyConstraint('master_id', 'salon_id')
    )
    op.create_table('salon_admin_salon',
    sa.Column('salon_admin_id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['salon_admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salon.id'], ),
    sa.PrimaryKeyConstraint('salon_admin_id', 'salon_id')
    )
    op.add_column('texture', sa.Column('master_id', sa.Integer(), nullable=False))
    op.alter_column('texture', 'file',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('texture', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'texture', 'user', ['master_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'texture', type_='foreignkey')
    op.alter_column('texture', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('texture', 'file',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('texture', 'master_id')
    op.drop_table('salon_admin_salon')
    op.drop_table('master_salon')
    op.drop_index(op.f('ix_event_datetime'), table_name='event')
    op.drop_table('event')
    op.drop_table('salon')
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
